name: CI/TEST
on: [push]
jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        working-directory: ./next-city
        run: yarn install
      - name: run tests
        working-directory: ./next-city
        run: yarn test
