name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: yarn install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: yarn build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: yarn test # will run `yarn test` command
